server:
  port: 9000

spring:
  # 应用名称
  application:
    name: @artifactId@
  # 环境配置
  profiles:
    active: @profiles.active@
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
      config:
        # 配置中心地址
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        # 命名空间，区分环境：开发环境、测试环境、预发布环境、⽣产环境，默认为public
        namespace: @profiles.active@
        # 分组，区分不同应⽤：同⼀个环境内，不同应⽤的配置，通过group来区分，默认为DEFAULT_GROUP
        group: @project.name@
        # 配置文件格式
        file-extension: yml
        # 导入共享的配置文件
        shared-configs[0]:
          data-id: application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
          group: ${spring.cloud.nacos.config.group}   # 默认为DEFAULT_GROUP
          #refresh: true         # 是否动态刷新，默认为false